### ISSUE TITLE
copyright clarification

### ISSUE THREAD

**Issue by anarcat** [getlantern/hex#1]
could you provide a copyright statement for this source code? under which license is it distributed?

i see the hex.go file refers to a "BSD-style license", but it refers to a non-existent LICENSE file. as there are many variations of "BSD-style" licenses, I think it would be better to explicitely add a license file or clarify in some way the copyright behind this code.

thanks

**Comment by meskio** [comment]
@oxtoacart what do you think? How can we help to clarify the license of this repo? Can #2 be accepted?

**Comment by oxtoacart** [comment]
Thanks @meskio, I've added a license.
